---
title: "Fish Data Stella"
author: "Stella"
date: "2024-02-22"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```

```{r}
ui <- dashboardPage(
  
  dashboardHeader(title = "Clownfish"),
  
  dashboardSidebar(disable=T),
  
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
    
    selectInput("x", "Select X Variable", choices = unique(), selected = ""),
  
    selectInput("y", "Select Y Variable", choices = unique(), selected = ""),

), 

box(title = "Plot of Penguins Data", width = 9,
  plotOutput("plot", width = "800px", height = "600px")
) # close the second box
) # close the row
) # close the dashboard body
) # close the ui

server <- function(input, output, session) {
  
  session$onSessionEnded(stopApp) #automatically stop the app when we close it
  
  output$plot <- renderPlot({
  ggplot(data=penguins, aes_string(x = input$x, y = input$y, color="species")) + 
      geom_point() + 
      theme_light()
    })
}

shinyApp(ui, server)
```

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "UC Campus Enrollment"),
  dashboardSidebar(disable=T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  radioButtons("x", "Select Ethnicity", choices = unique(UC_admit$Ethnicity), selected = "International"),
  selectInput("y", "Select Campus", choices = unique(UC_admit$Campus), selected = "Davis"),
  selectInput("z", "Select Admit Category", choices = unique(UC_admit$Category), selected = "Applicants")), 
  box(title = "UC Admissions", width = 8,
  plotOutput("plot", width = "600px", height = "500px")))))

server <- function(input, output, session) { 
  
output$plot <- renderPlot({
    UC_admit %>% 
    filter(Ethnicity==input$x & Campus==input$y & Category==input$z) %>% 
    ggplot(aes(x=Academic_Yr, y=FilteredCountFR)) + 
      geom_col(color="black", fill="skyblue", alpha=0.75) +
      theme_light(base_size = 18) +
      theme(axis.text.x = element_text(angle = 60, hjust = 1))+
      labs(x = "Year", y = "Enrollment")
  })
  
  session$onSessionEnded(stopApp)

  }

shinyApp(ui, server)
```

